### PR TITLE
request-filename condition fix

### PR DESCRIPTION
**Pull request by mkmayer**
Modifications for request-filename condition to got it working well (tested on Payara Glassfish Server).

Used and working urlrewrite.xml rule (ignored rest services url):

```
<rule>
  <name>HTML5 Redirect</name>
  <condition type="request-filename" operator="notfile"></condition> 
      <condition type="request-filename" operator="notdir"></condition> 
  <from>^((?!rest).)*$</from>
  <to type="redirect">%{context-path}/index.html</to>
</rule>
```

### CODE REVIEW

**Comment by dajester2013** [comment]
I can verify this patch fixes the problem on Tomcat 8.0.36.  Without the patch, the app folder is doubled:

```
\path\to\tomcat\webapp\<myApp>\<myApp>\file.html
```

**Comment by dajester2013** [comment]
@paultuckey any more thoughts about merging this request? it's a blocking issue (to the point that i had to deploy a similar patched version to our internal maven repo)

**Comment by mkmayer** [comment]
I don't need it anymore. I'm not using urlrewritfilter anymore. And if so, I can patch it myself manually. But if paultuckey wants, he can merge it. I tested it on Payara and I think it will fix the issue on other servers too (as you wrote with Tomcat 8.0.36), but have no time to test on all app servers :( Should be fine if Paul test it on app servers he deployed urlrewriter to and it can be merged then, it will fix the problem for other users...

**Comment by paultuckey** [comment]
I'd like to merge this but I want to check it works on many different types of app servers.  I used to have a setup for that, but I need to recreate it now.

**Comment by pearnaly** [comment]
Hi @paultuckey, ma we have a new release (4.0.5) with this fix please? I'm looking forward! Thank you!

**Comment by pearnaly** [comment]
...or maybe you have a workaround for the meantime?

**Pull request merged**
