### PR TITLE
exclude application path for REQUEST_URI and REQUEST_FILENAME

### PR DESCRIPTION
**Pull request by ftes**
For my use-case this change was essential. The context path (e.g. `/servlet`) was passed to some conditions (REQUEST_URI and REQUEST_FILENAME), as they received their URI to match against from `HttpServletRequest::getRequestUri()`. If for example `/index.html` was requested from a servlet with context path `/servlet`, then REQUEST_FILENAME matched against `/servlet/index.html`. As it performed this match within the servlet directory, it was looking for the file `/var/lib/tomcat8/webapps/servlet/servlet/index.html` (one servlet too many).

The context path can be configured by the servlet container (e.g. tomcat). So it is difficult to write rules that also include the context path. Therefore, I think the context path should not be used in the two conditions I mentioned.

I do not know however if this breaks compatibility with mod_rewrite. But here the semantics of a servlet container are just different from a web server like Apache.

Commit message details:
- most servlet containers expose a servlet under a certain path, e.g. /servlet
- prior to this change, this prefix was also passed to REQUEST_URI and REQUEST_FILENAME conditions
- e.g. the condition `RewriteCond %{REQUEST_URI} ^/index.html$` did not match a request to the servlets `index.html`, because the REQUEST_URI was actually `/servlet/index.html`

### CODE REVIEW

**Comment by melgish** [comment]
This pull request fixed a similar issue with 4.0.4 and 4.0.5-SNAPSHOT for me with tomcat 8.5.6.  
servlet context path was being repeated in request-filename path causing tests for existing files and folders to fail.

**Comment by paultuckey** [comment]
HI, this will no longer merge.  Are you able to fix and resubmit please?

**Comment by ftes** [comment]
I'm unsure if this PR is still needed. In the `master` branch I see these recent additions:

```
                	if (requestURI.startsWith(hsRequest.getContextPath() + "/")){
                		requestURI = requestURI.substring(hsRequest.getContextPath().length());
                	}
```

As far as I can tell, you already added the same logic I wanted to - in a slightly different way.

**Comment by paultuckey** [comment]
All good.  Thanks.

**Pull request closed without merging**
