### PR TITLE
Build Jakartified package for Servlet API 5.0

### LINKED ISSUE #239: Issue with JDK11 and Apache Tomcat 10
Hi,

My servlet application is unable to get deployed due to the below error.  It was working fine with JDK8 and Apache Tomcat 8.

--------------- /apache-tomcat-10/logs/localhost.2020-11-17.log ----------------
```
17-Nov-2020 09:39:43.241 SEVERE [main] org.apache.catalina.core.StandardContext.filterStart Exception starting filter [UrlRewriteFilter]
	java.lang.ClassCastException: class org.tuckey.web.filters.urlrewrite.UrlRewriteFilter cannot be cast to class jakarta.servlet.Filter (org.tuckey.web.filters.urlrewrite.UrlRewriteFilter is in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @1b73be9f; jakarta.servlet.Filter is in unnamed module of loader java.net.URLClassLoader @5f9d02cb)
		at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:250)
		at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:103)
		at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4515)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5152)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
```

Please help me out.

### PR DESCRIPTION
**Pull request by astappiev**
closes #239

### CODE REVIEW

**Comment by jetztgradnet** [comment]
Any further work on this issue? Anything we can do to help?
Apparently, there was a problem with this PR, but the error log is no longer available...
With many projects now making the switch to JakartaEE having this variant would be greatly desirable. Alternatively, we need to migrate to another solution which I would like to avoid, as the Tuckey URLRewriteFilter has all we need...

**Comment by astappiev** [comment]
I use a build created by `maven-shade-plugin` for more than a year in our project and everything works smoothly.
If there are any issues I might help to resolve, let me know.

**Comment by paultuckey** [comment]
Cool, thanks.  Am merging this.  I'm working on adding some modern container tests to verify this in an automated way.

**Comment by jetztgradnet** [comment]
Great, thanks, @paultuckey! Would you mind releasing this as a new version in Maven Central as well so we can make use of this in our softwre?

**Comment by paultuckey** [comment]
Handling this issue here https://github.com/paultuckey/urlrewritefilter/issues/251

**Pull request merged**
